version: "3.1"

services:
  media-service:
    container_name: media-service
    image: "media-service:1.0.0"
    hostname: smsotp
    restart: always
    ports:
      - "8082:8082"


networks:
  oneship_network: